# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/widgets/global_row.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GlobalRow(object):
    def setupUi(self, GlobalRow):
        GlobalRow.setObjectName("GlobalRow")
        GlobalRow.resize(694, 78)
        self.horizontalLayout = QtWidgets.QHBoxLayout(GlobalRow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(GlobalRow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEditName = QtWidgets.QLineEdit(GlobalRow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditName.sizePolicy().hasHeightForWidth())
        self.lineEditName.setSizePolicy(sizePolicy)
        self.lineEditName.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditName.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEditName.setBaseSize(QtCore.QSize(0, 0))
        self.lineEditName.setDragEnabled(False)
        self.lineEditName.setObjectName("lineEditName")
        self.horizontalLayout.addWidget(self.lineEditName)
        self.frame = QtWidgets.QFrame(GlobalRow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.comboBoxType = QtWidgets.QComboBox(self.frame)
        self.comboBoxType.setObjectName("comboBoxType")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxType)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.frameValue = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameValue.sizePolicy().hasHeightForWidth())
        self.frameValue.setSizePolicy(sizePolicy)
        self.frameValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameValue.setObjectName("frameValue")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameValue)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.frameValue)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frameValue)
        self.horizontalLayout.addWidget(self.frame)
        self.pushButtonDelete = QtWidgets.QPushButton(GlobalRow)
        self.pushButtonDelete.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout.addWidget(self.pushButtonDelete)

        self.retranslateUi(GlobalRow)
        QtCore.QMetaObject.connectSlotsByName(GlobalRow)

    def retranslateUi(self, GlobalRow):
        _translate = QtCore.QCoreApplication.translate
        GlobalRow.setWindowTitle(_translate("GlobalRow", "Form"))
        self.label_3.setText(_translate("GlobalRow", "Name"))
        self.comboBoxType.setItemText(0, _translate("GlobalRow", "Integer"))
        self.comboBoxType.setItemText(1, _translate("GlobalRow", "Float"))
        self.comboBoxType.setItemText(2, _translate("GlobalRow", "String"))
        self.comboBoxType.setItemText(3, _translate("GlobalRow", "Boolean"))
        self.label.setText(_translate("GlobalRow", "Type"))
        self.label_2.setText(_translate("GlobalRow", "Value"))
        self.pushButtonDelete.setText(_translate("GlobalRow", "X"))

