# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 651)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName("splitter")
        self.filesFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesFrame.sizePolicy().hasHeightForWidth())
        self.filesFrame.setSizePolicy(sizePolicy)
        self.filesFrame.setMinimumSize(QtCore.QSize(100, 0))
        self.filesFrame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.filesFrame.setBaseSize(QtCore.QSize(200, 0))
        self.filesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filesFrame.setObjectName("filesFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.filesFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filesLabel = QtWidgets.QLabel(self.filesFrame)
        self.filesLabel.setObjectName("filesLabel")
        self.verticalLayout.addWidget(self.filesLabel)
        self.filesTreeView = QtWidgets.QTreeView(self.filesFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesTreeView.sizePolicy().hasHeightForWidth())
        self.filesTreeView.setSizePolicy(sizePolicy)
        self.filesTreeView.setMinimumSize(QtCore.QSize(0, 0))
        self.filesTreeView.setSizeIncrement(QtCore.QSize(0, 0))
        self.filesTreeView.setBaseSize(QtCore.QSize(0, 0))
        self.filesTreeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.filesTreeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.filesTreeView.setObjectName("filesTreeView")
        self.filesTreeView.header().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.filesTreeView)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 318, 584))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 744, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuCreate = QtWidgets.QMenu(self.menubar)
        self.menuCreate.setObjectName("menuCreate")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionScenario = QtWidgets.QAction(MainWindow)
        self.actionScenario.setObjectName("actionScenario")
        self.actionItem = QtWidgets.QAction(MainWindow)
        self.actionItem.setObjectName("actionItem")
        self.actionFunction = QtWidgets.QAction(MainWindow)
        self.actionFunction.setObjectName("actionFunction")
        self.actionToWeb = QtWidgets.QAction(MainWindow)
        self.actionToWeb.setObjectName("actionToWeb")
        self.actionToFile = QtWidgets.QAction(MainWindow)
        self.actionToFile.setObjectName("actionToFile")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionStandard = QtWidgets.QAction(MainWindow)
        self.actionStandard.setObjectName("actionStandard")
        self.actionDebug = QtWidgets.QAction(MainWindow)
        self.actionDebug.setObjectName("actionDebug")
        self.menuExport.addAction(self.actionToWeb)
        self.menuExport.addAction(self.actionToFile)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuCreate.addAction(self.actionScenario)
        self.menuCreate.addAction(self.actionItem)
        self.menuCreate.addAction(self.actionFunction)
        self.menuTools.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuRun.addAction(self.actionStandard)
        self.menuRun.addAction(self.actionDebug)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuCreate.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TRPG Creator"))
        self.filesLabel.setText(_translate("MainWindow", "Files"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuExport.setTitle(_translate("MainWindow", "&Export"))
        self.menuCreate.setTitle(_translate("MainWindow", "&Create"))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuRun.setTitle(_translate("MainWindow", "&Run"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionScenario.setText(_translate("MainWindow", "&Scenario"))
        self.actionItem.setText(_translate("MainWindow", "&Item"))
        self.actionFunction.setText(_translate("MainWindow", "&Function"))
        self.actionToWeb.setText(_translate("MainWindow", "To &Web..."))
        self.actionToWeb.setShortcut(_translate("MainWindow", "Ctrl+E, W"))
        self.actionToFile.setText(_translate("MainWindow", "To &File..."))
        self.actionToFile.setShortcut(_translate("MainWindow", "Ctrl+E, F"))
        self.actionSettings.setText(_translate("MainWindow", "&Settings"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+F7"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F2"))
        self.actionDocumentation.setText(_translate("MainWindow", "&Documentation"))
        self.actionDocumentation.setShortcut(_translate("MainWindow", "F1"))
        self.actionUndo.setText(_translate("MainWindow", "&Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionStandard.setText(_translate("MainWindow", "&Standard"))
        self.actionStandard.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionDebug.setText(_translate("MainWindow", "&Debug"))
        self.actionDebug.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))

